// 'Specter' Security Engine — Speculative Threat Modeling (STORY-001)
// Acts as a Red Team agent that generates and exploits attack vectors.
// Integrated into the Forge pipeline to ensure adversarial hardening.

import { Agent, type AgentContext, type AgentResult } from './agent.js';
import { getLogger } from '../utils/logger.js';
import type { MessageType } from '../types.js';
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { execSync, execFileSync } from 'node:child_process';

/**
 * Represents a speculative attack vector generated by Specter.
 */
export interface AttackVector {
  id: string;
  title: string;
  description: string;
  severity: 'critical' | 'high' | 'medium' | 'low';
  type: 'logic_bypass' | 'auth_flaw' | 'data_leak' | 'injection' | 'other';
  exploitSimCommand?: string; // Command to attempt exploitation (e.g. curl)
  mitigationAdvice: string;
  status: 'draft' | 'simulating' | 'exploited' | 'mitigated' | 'false_positive';
}

/**
 * Result of an adversarial simulation attempt.
 */
export interface SimulationResult {
  vectorId: string;
  success: boolean; // true if exploit worked
  output: string;
  error?: string;
  timestamp: string;
}

/**
 * Final report generated by Specter for a feature implementation.
 */
export interface SpecterReport {
  status: 'PASS' | 'FAIL' | 'DRAFT';
  vectors: AttackVector[];
  simulations: SimulationResult[];
  resilienceScore: number; // 0-100
  summary: string;
}

/**
 * The Specter Security Engine.
 * 
 * It analyzes code changes, generates speculative attack vectors using LLM,
 * and attempts to verify them through local simulations.
 */
export class SpecterEngine extends Agent {
  constructor() {
    super('specter', 'Specter Security Engine', 'FULL');
  }

  /**
   * Run the Specter analysis on the current context.
   * 
   * @param task - The PRD or task description.
   * @param context - Execution context including workDir and config.
   */
  protected async run(task: string, context: AgentContext): Promise<AgentResult> {
    const log = getLogger();
    log.info('specter', 'analysis_start', { workDir: context.workDir });

    this.setProgress(0, 100, 'Generating speculative attack vectors...');
    
    // 1. Get recent diff
    let diff = '';
    try {
      diff = execSync('git diff HEAD', { cwd: context.workDir, encoding: 'utf-8' });
    } catch {
      // Fallback or ignore
    }

    // 2. Generate vectors
    const vectors = await this.generateVectors(diff, task, context);
    this.addDecision('Vectors Generated', `Specter identified ${vectors.length} potential attack vectors.`);
    
    if (vectors.length === 0) {
      this.setProgress(100, 100, 'No speculative vectors identified.');
      const finalReport: SpecterReport = {
        status: 'PASS',
        vectors: [],
        simulations: [],
        resilienceScore: 100,
        summary: 'No speculative attack vectors were identified for these changes.',
      };
      return this.buildResult('completed', JSON.stringify(finalReport, null, 2));
    }

    // 3. Simulate vectors
    const simulations: SimulationResult[] = [];
    let exploitedCount = 0;

    for (let i = 0; i < vectors.length; i++) {
      const vector = vectors[i];
      this.setProgress(20 + (i / vectors.length) * 60, 100, `Simulating: ${vector.title}`);
      
      vector.status = 'simulating';
      const simResult = await this.runSimulation(vector, context);
      simulations.push(simResult);

      if (simResult.success) {
        vector.status = 'exploited';
        exploitedCount++;
        log.error('specter', 'vulnerability_proven', { vectorId: vector.id, title: vector.title });
      } else {
        vector.status = 'mitigated';
      }
    }

    // 4. Final report
    const resilienceScore = Math.max(0, 100 - (exploitedCount * 25));
    const report: SpecterReport = {
      status: exploitedCount > 0 ? 'FAIL' : 'PASS',
      vectors,
      simulations,
      resilienceScore,
      summary: exploitedCount > 0 
        ? `Specter proved ${exploitedCount} vulnerabilities exist.` 
        : 'All speculative attack vectors were successfully mitigated or blocked.',
    };

    this.setProgress(100, 100, `Analysis complete. Score: ${resilienceScore}`);
    
    if (exploitedCount > 0) {
      this.emit('failed', { exploited: exploitedCount });
      return this.buildResult('failed', JSON.stringify(report, null, 2));
    }

    return this.buildResult('completed', JSON.stringify(report, null, 2));
  }

  /**
   * Generate attack vectors based on code changes (STORY-002).
   */
  async generateVectors(diff: string, prd: string, context: AgentContext): Promise<AttackVector[]> {
    const log = getLogger();
    log.info('specter', 'generating_vectors', { diffSize: diff.length });

    const promptPath = join(context.workDir, 'sf_cli/src/prompts/specter-red-team.md');
    if (!existsSync(promptPath)) {
      log.warn('specter', 'prompt_not_found', { path: promptPath });
      return [];
    }

    const promptTemplate = readFileSync(promptPath, 'utf-8');
    const systemPrompt = promptTemplate
      .replace('{{prd}}', prd)
      .replace('{{diff}}', diff);

    const result = await this.runLoop(
      'You are a Red Team agent. Return ONLY raw JSON array of AttackVector objects.',
      'Generate 3 speculative attack vectors for the provided code changes.',
      context,
      { maxTurns: 1 }
    );

    try {
      const content = result.content.trim();
      const jsonMatch = content.match(/\[[\s\S]*\]/);
      const json = jsonMatch ? jsonMatch[0] : content;
      const vectors = JSON.parse(json) as AttackVector[];
      return vectors.map(v => ({ ...v, status: 'draft' as const }));
    } catch (err) {
      log.error('specter', 'parse_failed', { error: String(err), content: result.content });
      return [];
    }
  }

  /**
   * Run an adversarial simulation for a vector (STORY-003).
   *
   * SECURITY: the model-authored `exploitSimCommand` is NEVER executed as a
   * command. We extract only a URL from it, validate that URL is a loopback
   * HTTP(S) target with no userinfo, and issue a FIXED `curl` invocation via
   * `execFileSync` (no shell, no argument taken from the model except the
   * validated URL). Execution is opt-in: it runs only when
   * `SF_SPECTER_SIMULATE` is truthy. When disabled (the default), the vector
   * is reported as un-simulated so the static analysis + mitigation advice
   * still ship, but no attacker-influenced probe fires.
   */
  async runSimulation(vector: AttackVector, context: AgentContext): Promise<SimulationResult> {
    const log = getLogger();
    const command = vector.exploitSimCommand;
    const now = () => new Date().toISOString();

    if (!command) {
      return { vectorId: vector.id, success: false, output: 'No simulation command provided', timestamp: now() };
    }

    // Opt-in gate — simulation is OFF by default (see method doc).
    const simulationEnabled =
      process.env.SF_SPECTER_SIMULATE === '1' || process.env.SF_SPECTER_SIMULATE === 'true';
    if (!simulationEnabled) {
      return {
        vectorId: vector.id,
        success: false,
        output: 'Simulation disabled (set SF_SPECTER_SIMULATE=1 to enable loopback probes). Vector reported from static analysis only.',
        timestamp: now(),
      };
    }

    // Extract a validated loopback URL. Anything that is not a safe loopback
    // HTTP(S) probe is refused — never executed as a shell command.
    const probeUrl = SpecterEngine.extractLoopbackProbe(command);
    if (!probeUrl) {
      log.warn('specter', 'unsafe_command_blocked', { command });
      return {
        vectorId: vector.id,
        success: false,
        output: 'Blocked: only loopback (localhost/127.0.0.1/::1) HTTP(S) probes are permitted for simulation.',
        timestamp: now(),
      };
    }

    log.info('specter', 'running_simulation', { vectorId: vector.id, probeUrl });

    try {
      // Fixed argv — the only model-derived value is the validated URL.
      const output = execFileSync('curl', ['-s', '--max-time', '5', probeUrl], {
        cwd: context.workDir,
        timeout: 10000,
        encoding: 'utf-8',
        stdio: ['ignore', 'pipe', 'pipe'],
      });

      return { vectorId: vector.id, success: true, output, timestamp: now() };
    } catch (err: any) {
      const output = (err.stdout || '') + (err.stderr || '');
      log.debug('specter', 'simulation_failed_or_blocked', { vectorId: vector.id, error: err.message });
      return { vectorId: vector.id, success: false, output: output || err.message, timestamp: now() };
    }
  }

  /**
   * Extract a safe loopback HTTP(S) URL from a model-authored command string,
   * or return null if none is present or the URL is not a safe loopback target.
   *
   * Hardening applied:
   *  - the URL is parsed with the WHATWG `URL` parser (no substring matching);
   *  - protocol must be http:/https:;
   *  - hostname must be an exact loopback literal (defeats the
   *    `http://localhost@attacker.com` userinfo trick, which parses to
   *    hostname `attacker.com`);
   *  - any userinfo (username/password) is rejected outright.
   * The returned value is `url.href` — a normalized string, not the raw input.
   */
  static extractLoopbackProbe(command: string): string | null {
    const LOOPBACK = new Set(['localhost', '127.0.0.1', '0.0.0.0', '::1', '[::1]']);
    const match = command.match(/https?:\/\/[^\s'"`|;&$()<>\\]+/i);
    if (!match) return null;
    let url: URL;
    try {
      url = new URL(match[0]);
    } catch {
      return null;
    }
    if (url.protocol !== 'http:' && url.protocol !== 'https:') return null;
    if (url.username !== '' || url.password !== '') return null;
    if (!LOOPBACK.has(url.hostname.toLowerCase())) return null;
    return url.href;
  }
}
