// 'Specter' Security Engine — Speculative Threat Modeling (STORY-001)
// Acts as a Red Team agent that generates and exploits attack vectors.
// Integrated into the Forge pipeline to ensure adversarial hardening.

import { Agent, type AgentContext, type AgentResult } from './agent.js';
import { getLogger } from '../utils/logger.js';
import type { MessageType } from '../types.js';
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { execSync } from 'node:child_process';

/**
 * Represents a speculative attack vector generated by Specter.
 */
export interface AttackVector {
  id: string;
  title: string;
  description: string;
  severity: 'critical' | 'high' | 'medium' | 'low';
  type: 'logic_bypass' | 'auth_flaw' | 'data_leak' | 'injection' | 'other';
  exploitSimCommand?: string; // Command to attempt exploitation (e.g. curl)
  mitigationAdvice: string;
  status: 'draft' | 'simulating' | 'exploited' | 'mitigated' | 'false_positive';
}

/**
 * Result of an adversarial simulation attempt.
 */
export interface SimulationResult {
  vectorId: string;
  success: boolean; // true if exploit worked
  output: string;
  error?: string;
  timestamp: string;
}

/**
 * Final report generated by Specter for a feature implementation.
 */
export interface SpecterReport {
  status: 'PASS' | 'FAIL' | 'DRAFT';
  vectors: AttackVector[];
  simulations: SimulationResult[];
  resilienceScore: number; // 0-100
  summary: string;
}

/**
 * The Specter Security Engine.
 * 
 * It analyzes code changes, generates speculative attack vectors using LLM,
 * and attempts to verify them through local simulations.
 */
export class SpecterEngine extends Agent {
  constructor() {
    super('specter', 'Specter Security Engine', 'FULL');
  }

  /**
   * Run the Specter analysis on the current context.
   * 
   * @param task - The PRD or task description.
   * @param context - Execution context including workDir and config.
   */
  protected async run(task: string, context: AgentContext): Promise<AgentResult> {
    const log = getLogger();
    log.info('specter', 'analysis_start', { workDir: context.workDir });

    this.setProgress(0, 100, 'Generating speculative attack vectors...');
    
    // 1. Get recent diff
    let diff = '';
    try {
      diff = execSync('git diff HEAD', { cwd: context.workDir, encoding: 'utf-8' });
    } catch {
      // Fallback or ignore
    }

    // 2. Generate vectors
    const vectors = await this.generateVectors(diff, task, context);
    this.addDecision('Vectors Generated', `Specter identified ${vectors.length} potential attack vectors.`);
    
    if (vectors.length === 0) {
      this.setProgress(100, 100, 'No speculative vectors identified.');
      const finalReport: SpecterReport = {
        status: 'PASS',
        vectors: [],
        simulations: [],
        resilienceScore: 100,
        summary: 'No speculative attack vectors were identified for these changes.',
      };
      return this.buildResult('completed', JSON.stringify(finalReport, null, 2));
    }

    // 3. Simulate vectors
    const simulations: SimulationResult[] = [];
    let exploitedCount = 0;

    for (let i = 0; i < vectors.length; i++) {
      const vector = vectors[i];
      this.setProgress(20 + (i / vectors.length) * 60, 100, `Simulating: ${vector.title}`);
      
      vector.status = 'simulating';
      const simResult = await this.runSimulation(vector, context);
      simulations.push(simResult);

      if (simResult.success) {
        vector.status = 'exploited';
        exploitedCount++;
        log.error('specter', 'vulnerability_proven', { vectorId: vector.id, title: vector.title });
      } else {
        vector.status = 'mitigated';
      }
    }

    // 4. Final report
    const resilienceScore = Math.max(0, 100 - (exploitedCount * 25));
    const report: SpecterReport = {
      status: exploitedCount > 0 ? 'FAIL' : 'PASS',
      vectors,
      simulations,
      resilienceScore,
      summary: exploitedCount > 0 
        ? `Specter proved ${exploitedCount} vulnerabilities exist.` 
        : 'All speculative attack vectors were successfully mitigated or blocked.',
    };

    this.setProgress(100, 100, `Analysis complete. Score: ${resilienceScore}`);
    
    if (exploitedCount > 0) {
      this.emit('failed', { exploited: exploitedCount });
      return this.buildResult('failed', JSON.stringify(report, null, 2));
    }

    return this.buildResult('completed', JSON.stringify(report, null, 2));
  }

  /**
   * Generate attack vectors based on code changes (STORY-002).
   */
  async generateVectors(diff: string, prd: string, context: AgentContext): Promise<AttackVector[]> {
    const log = getLogger();
    log.info('specter', 'generating_vectors', { diffSize: diff.length });

    const promptPath = join(context.workDir, 'sf_cli/src/prompts/specter-red-team.md');
    if (!existsSync(promptPath)) {
      log.warn('specter', 'prompt_not_found', { path: promptPath });
      return [];
    }

    const promptTemplate = readFileSync(promptPath, 'utf-8');
    const systemPrompt = promptTemplate
      .replace('{{prd}}', prd)
      .replace('{{diff}}', diff);

    const result = await this.runLoop(
      'You are a Red Team agent. Return ONLY raw JSON array of AttackVector objects.',
      'Generate 3 speculative attack vectors for the provided code changes.',
      context,
      { maxTurns: 1 }
    );

    try {
      const content = result.content.trim();
      const jsonMatch = content.match(/\[[\s\S]*\]/);
      const json = jsonMatch ? jsonMatch[0] : content;
      const vectors = JSON.parse(json) as AttackVector[];
      return vectors.map(v => ({ ...v, status: 'draft' as const }));
    } catch (err) {
      log.error('specter', 'parse_failed', { error: String(err), content: result.content });
      return [];
    }
  }

  /**
   * Run an adversarial simulation for a vector (STORY-003).
   */
  async runSimulation(vector: AttackVector, context: AgentContext): Promise<SimulationResult> {
    const log = getLogger();
    const command = vector.exploitSimCommand;

    if (!command) {
      return {
        vectorId: vector.id,
        success: false,
        output: 'No simulation command provided',
        timestamp: new Date().toISOString(),
      };
    }

    // Safety guard: only allow localhost/127.0.0.1 for now
    if (!this.isSafeCommand(command)) {
      log.warn('specter', 'unsafe_command_blocked', { command });
      return {
        vectorId: vector.id,
        success: false,
        output: 'Blocked: Simulation command must only target localhost or 127.0.0.1 for safety.',
        timestamp: new Date().toISOString(),
      };
    }

    log.info('specter', 'running_simulation', { vectorId: vector.id, command });

    try {
      const output = execSync(command, {
        cwd: context.workDir,
        timeout: 10000,
        encoding: 'utf-8',
        stdio: ['pipe', 'pipe', 'pipe'],
      });

      return {
        vectorId: vector.id,
        success: true, // success = attack worked
        output,
        timestamp: new Date().toISOString(),
      };
    } catch (err: any) {
      const output = (err.stdout || '') + (err.stderr || '');
      log.debug('specter', 'simulation_failed_or_blocked', { vectorId: vector.id, error: err.message });
      return {
        vectorId: vector.id,
        success: false, // attack failed (good for security, bad for exploitation)
        output: output || err.message,
        timestamp: new Date().toISOString(),
      };
    }
  }

  /**
   * Basic safety check for simulation commands.
   */
  private isSafeCommand(command: string): boolean {
    // Whitelist localhost and 127.0.0.1. Block everything else.
    const urlPattern = /https?:\/\/(localhost|127\.0\.0\.1|0\.0\.0\.0)(:\d+)?/i;
    // If it's a curl command, it must match the localhost pattern.
    if (command.includes('curl') || command.includes('http')) {
      return urlPattern.test(command);
    }
    // For other commands, we might need stricter checks.
    return true; 
  }
}
