import { exec, commandExists } from "./exec-utils.js";
import { readFile, writeFile, access } from "fs/promises";
import path from "path";

export interface NginxConfigResult {
  generated: boolean;
  config: string;
  path: string | null;
  valid: boolean;
  validationOutput: string;
  duration: number;
}

export interface NginxValidateResult {
  valid: boolean;
  output: string;
  duration: number;
}

/**
 * Generate an nginx reverse proxy config for an app.
 */
export function generateNginxConfig(options: {
  domain: string;
  port: number;
  ssl?: boolean;
  certPath?: string;
  keyPath?: string;
  staticCachePaths?: string[];
}): string {
  const { domain, port, ssl = true } = options;
  const certPath = options.certPath || `/etc/letsencrypt/live/${domain}/fullchain.pem`;
  const keyPath = options.keyPath || `/etc/letsencrypt/live/${domain}/privkey.pem`;
  const staticPaths = options.staticCachePaths || ["/_next/static/"];

  const lines: string[] = [];

  // HTTP → HTTPS redirect
  lines.push(`# ${domain} — generated by SkillFoundry`);
  lines.push("server {");
  lines.push("    listen 80;");
  lines.push("    listen [::]:80;");
  lines.push(`    server_name ${domain};`);
  lines.push("");
  lines.push("    location /.well-known/acme-challenge/ {");
  lines.push("        root /var/www/certbot;");
  lines.push("    }");
  lines.push("");
  lines.push("    location / {");
  lines.push("        return 301 https://$server_name$request_uri;");
  lines.push("    }");
  lines.push("}");
  lines.push("");

  if (ssl) {
    lines.push("server {");
    lines.push("    listen 443 ssl http2;");
    lines.push("    listen [::]:443 ssl http2;");
    lines.push(`    server_name ${domain};`);
    lines.push("");
    lines.push(`    ssl_certificate ${certPath};`);
    lines.push(`    ssl_certificate_key ${keyPath};`);
    lines.push("    ssl_protocols TLSv1.2 TLSv1.3;");
    lines.push("    ssl_prefer_server_ciphers off;");
    lines.push("    ssl_session_cache shared:SSL:10m;");
    lines.push("");
    lines.push("    # Security headers");
    lines.push('    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;');
    lines.push('    add_header X-Frame-Options "DENY" always;');
    lines.push('    add_header X-Content-Type-Options "nosniff" always;');
    lines.push('    add_header Referrer-Policy "strict-origin-when-cross-origin" always;');
    lines.push("");
    lines.push("    # Gzip");
    lines.push("    gzip on;");
    lines.push("    gzip_vary on;");
    lines.push("    gzip_min_length 1024;");
    lines.push("    gzip_types text/plain text/css text/javascript application/javascript application/json image/svg+xml;");
    lines.push("");
    lines.push("    # Reverse proxy");
    lines.push("    location / {");
    lines.push(`        proxy_pass http://127.0.0.1:${port};`);
    lines.push("        proxy_http_version 1.1;");
    lines.push("        proxy_set_header Upgrade $http_upgrade;");
    lines.push('        proxy_set_header Connection "upgrade";');
    lines.push("        proxy_set_header Host $host;");
    lines.push("        proxy_set_header X-Real-IP $remote_addr;");
    lines.push("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;");
    lines.push("        proxy_set_header X-Forwarded-Proto $scheme;");
    lines.push("        proxy_cache_bypass $http_upgrade;");
    lines.push("        proxy_read_timeout 90;");
    lines.push("    }");
    lines.push("");

    // Static asset caching
    for (const staticPath of staticPaths) {
      lines.push(`    location ${staticPath} {`);
      lines.push(`        proxy_pass http://127.0.0.1:${port};`);
      lines.push("        expires 1y;");
      lines.push('        add_header Cache-Control "public, immutable";');
      lines.push("        access_log off;");
      lines.push("    }");
      lines.push("");
    }

    lines.push("    # Block hidden files");
    lines.push("    location ~ /\\. {");
    lines.push("        deny all;");
    lines.push("        access_log off;");
    lines.push("    }");
    lines.push("");
    lines.push(`    access_log /var/log/nginx/${domain}.access.log;`);
    lines.push(`    error_log /var/log/nginx/${domain}.error.log;`);
    lines.push("}");
  }

  return lines.join("\n");
}

/**
 * Validate an nginx configuration.
 */
export async function validateNginxConfig(
  configPath?: string
): Promise<NginxValidateResult> {
  const start = Date.now();

  if (!(await commandExists("nginx"))) {
    return {
      valid: false,
      output: "nginx not installed",
      duration: Date.now() - start,
    };
  }

  const args = ["-t"];
  if (configPath) args.push("-c", configPath);

  const result = await exec("nginx", args, { timeout: 10000 });

  return {
    valid: result.success || result.stderr.includes("test is successful"),
    output: (result.stdout + result.stderr).trim(),
    duration: result.duration,
  };
}

/**
 * Generate config, write to sites-available, and validate.
 */
export async function setupNginxForApp(options: {
  domain: string;
  port: number;
  ssl?: boolean;
  writePath?: string;
}): Promise<NginxConfigResult> {
  const start = Date.now();
  const config = generateNginxConfig(options);
  const writePath = options.writePath ||
    `/etc/nginx/sites-available/${options.domain}`;

  let written = false;
  try {
    await writeFile(writePath, config);
    written = true;
  } catch {
    // Permission denied — return config for manual install
  }

  const validation = written
    ? await validateNginxConfig()
    : { valid: false, output: "Config not written (permission denied). Manual install required." };

  return {
    generated: true,
    config,
    path: written ? writePath : null,
    valid: validation.valid,
    validationOutput: validation.output,
    duration: Date.now() - start,
  };
}
